feat: stmt over websocket
taosdata/driver-go pull request #128
Opened 2022-10-26 10:06 UTC by huskar-t

2022-10-27 02:53 UTC, sunpe requested changes
ws/tmq/consumer_test.go L94

2022-10-27 02:53 UTC, sunpe commented on ws/tmq/consumer_test.go
> +	//defer cleanEnv()
不需要clean了？

2022-10-27 07:46 UTC, huolibo approved these changes
LGTM

2022-10-28 03:00 UTC, sunpe approved these changes
LGTM

2022-10-28 03:09 UTC, huolibo approved these changes
LGTM

2022-10-28 04:47 UTC, merged