feat: add platform token parameter
taosdata/driver-go pull request #82
Opened 2022-05-06 08:39 UTC by huskar-t

TD-15079

2022-05-06 09:11 UTC, huolibo approved these changes
LGTM

2022-05-06 09:11 UTC, zitsen approved these changes
LGTM

2022-05-06 11:22 UTC, sangshuduo commented on examples/platform/main.go
> +	db, err := sql.Open("taosRestful", "root:taosdata@http(192.168.1.163:8085)/?platformToken=c37ef4dbec8708c0227b4e8cb84ffffb9b8711a1")
need be consistent with connector

2022-05-06 11:22 UTC, sangshuduo requested changes
see my comment

2022-05-12 01:17 UTC, huskar-t commented
after readjustment

2022-05-12 01:58 UTC, huolibo approved these changes
LGTM

2022-05-12 02:24 UTC, sangshuduo commented on taosRestful/connection.go
> +	//loginUrl := &url.URL{
we should avoid keeping too many lines of unused code in the release branch.

2022-05-12 02:24 UTC, sangshuduo approved these changes
LGTM with a comment

2022-05-12 02:31 UTC, merged